---
header_image: /uploads/web-mg-5135.jpg
intro_images:
  - image: /img/kapper-amsterdam-koffijberg1.jpg
  - image: /img/kapper-amsterdam-koffijberg2.jpg
  - image: /img/kapper-amsterdam-koffijberg3.jpg
  - image: /img/kapper-amsterdam-koffijberg4.jpg
  - image: /img/kapper-amsterdam-koffijberg5.jpg
  - image: /img/kapper-amsterdam-koffijberg6.jpg
  - image: /img/kapper-amsterdam-koffijberg7.jpg
  - image: /img/kapper-amsterdam-koffijberg8.jpg
---